workflows:
  android-workflow:
    name: Android Build
    environment:
      android_signing:
        - keystore: /path/to/my-release-key.keystore
          keystore_password: EncryptedKeystorePassword
          key_alias: my-key-alias  # Use the alias you found
          key_password: EncryptedKeyPassword
          type: jks
          group: com.example
          source: build.gradle
