workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.islamic_lifestyle_app"
        KEYSTORE_PASSWORD: "fmt2000fmt"
        KEY_ALIAS: "my_key_alias"
        KEY_PASSWORD: "fmt2000fmt"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Copy keystore to project
        script: |
          echo "Copying keystore to project directory..."
          mkdir -p $CM_BUILD_DIR/android/app/keystore
          cp $FCI_BUILD_DIR/my-release-key.keystore $CM_BUILD_DIR/android/app/keystore/
          echo "Keystore copied to $CM_BUILD_DIR/android/app/keystore/my-release-key.keystore"
      - name: Configure Gradle for signing
        script: |
          cat >> "$CM_BUILD_DIR/android/app/build.gradle" << 'EOF'
          
          android {
              signingConfigs {
                  release {
                      storeFile file('keystore/my-release-key.keystore')
                      storePassword "fmt2000\\$\\$"
                      keyAlias "my_key_alias"
                      keyPassword "fmt2000\\$\\$"
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                  }
              }
          }
          EOF
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build App Bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com

  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.islamicLifestyleApp
      groups:
        - app_store
      vars:
        APP_ID: 1234567890
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Build ipa for distribution
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release -archivePath Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./build
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com

  web-workflow:
    name: Web Build
    instance_type: linux
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Build Web
        script: |
          flutter build web --release
    artifacts:
      - build/web/*
    publishing:
      email:
        recipients:
          - user@example.com
