workflows:
  android-workflow:
    name: Android Build
    environment:
      android_signing:
        - name: my-release-key
          filePath: $CM_KEYSTORE_FILE_PATH  # Path to the keystore file (use an environment variable if needed)
          keystore_password: $CM_KEYSTORE_PASSWORD  # Encrypted keystore password (use an environment variable)
          key_alias: $CM_KEY_ALIAS  # Key alias (use an environment variable)
          key_password: $CM_KEY_PASSWORD  # Key password (use an environment variable)
          type: secure_environment_variable  # The type expected here is "secure_environment_variable"
