workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.islamic_lifestyle_app"
        KEYSTORE_PASSWORD: "fmt2000fmt"
        KEY_ALIAS: "my_key_alias"
        KEY_PASSWORD: "fmt2000fmt"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Copy keystore to project
        script: |
          echo "Copying keystore to project directory..."
          mkdir -p $CM_BUILD_DIR/android/app/keystore
          cp $FCI_BUILD_DIR/my-release-key.keystore $CM_BUILD_DIR/android/app/keystore/
          echo "Keystore copied to $CM_BUILD_DIR/android/app/keystore/my-release-key.keystore"
      - name: Configure Gradle for signing
        script: |
          cat >> "$CM_BUILD_DIR/android/app/build.gradle" << 'EOF'

          android {
              signingConfigs {
                  release {
                      storeFile file('keystore/my-release-key.keystore')
                      storePassword "fmt2000fmt"
                      keyAlias "my_key_alias"
                      keyPassword "fmt2000fmt"
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                  }
              }
          }
          EOF
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
