workflows:
  android-workflow:
    name: Android Build
    environment:
      android_signing:
        - keystore: YOUR_ENCRYPTED_KEYSTORE_REFERENCE
          keystore_password: YOUR_ENCRYPTED_PASSWORD
          key_alias: my-key-alias  # Use the correct alias name
          key_password: YOUR_ENCRYPTED_KEY_PASSWORD
