workflows:
  android-workflow:
    name: Android Build
    environment:
      android_signing:
        - name: my-release-key
          filePath: path/to/my-release-key.keystore
          keystore_password: EncryptedKeystorePassword
          key_alias: my-key-alias
          key_password: EncryptedKeyPassword
          type: jks  # or 'pkcs12' depending on your keystore type
          group: com.example
          source: build.gradle
